use_frameworks!

platform :ios, '8.0'
project '../Baisi.xcodeproj'

target 'Baisi' do

pod 'QorumLogs' 

pod 'Alamofire', '~> 4.4.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SwiftyJSON'
pod 'Kingfisher'



end

